### ISSUE TITLE
Receiving React 15 propTypes validation deprecation warning from SideEffect.render

### ISSUE THREAD

**Issue by jeffhandley** [gaearon/react-side-effect#26]
When rendering components using `withSideEffect`, I am getting the following warning from React (15.0.2):

```
Warning: You are manually calling a React.PropTypes validation function for the {prop} prop on {component}. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
    at printWarning (.../node_modules/fbjs/lib/warning.js:36:17)
    at warning (.../node_modules/fbjs/lib/warning.js:60:22)
    at checkType (.../node_modules/react/lib/ReactPropTypes.js:134:51)
    at checkPropTypes (.../node_modules/react/lib/ReactElementValidator.js:178:36)
    at validatePropTypes (.../node_modules/react/lib/ReactElementValidator.js:208:5)
    at Object.ReactElementValidator.createElement (.../node_modules/react/lib/ReactElementValidator.js:242:5)
    at SideEffect.render (.../node_modules/react-side-effect/lib/index.js:102:35)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (.../node_modules/react/lib/ReactCompositeComponent.js:815:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (.../node_modules/react/lib/ReactCompositeComponent.js:841:32)
```

It looks like this is possibly a false positive on the detection of manual propTypes validation.

**Comment by lourd** [comment]
Hi @jeffhandley, thanks for the issue report! Are you still seeing this? I'm not able to reproduce the bug. Please re-open the issue if you are and post details of how to reproduce
