### ISSUE TITLE
Problems in installation

### ISSUE THREAD

**Issue by sarahmarciano** [gaearon/react-side-effect#38]
after installing this library I'm not able to run react-native start and get this error:
(I'm installing it in a react native project)
`module.js:472
    throw err;
    ^

Error: Cannot find module 'anymatch'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sarahm/dev/closapp2/node_modules/jest-haste-map/node_modules/sane/src/common.js:3:16)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/sarahm/dev/closapp2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)`

**Comment by lourd** [comment]
Hi Sarah, thanks for your report.

I don't believe this library is the cause of the issue you're facing. It does not use the `anymatch` module, and it isn't in that trace. Are you sure you completely isolated the installation of this library to the cause of react native not starting for you?

**Comment by sarahmarciano** [comment]
Yes, indeed this library was not the cause of the issue
Thank you for your quick response, and sorry for disturbing you

**Comment by nadeem36212** [comment]
helloo sarah.............

i am also having same issue, I have installed image-picker library and it doesn't installed correctly, after it when i run my project it giving me same error. I have uninstalled that library still the error is remained..

so how did u fix it can u plz tell me.?

**Comment by sarahmarciano** [comment]
try to delete the package-lock.json and then run npm install
